app = "amibot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "prod.Dockerfile"

[env]
  PORT = "8000"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8000
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 50
    soft_limit = 40

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_timeout = 0
    timeout = "2s"

